resolver: nightly-2021-11-19

allow-newer: true
extra-deps:
  - git: https://github.com/Haskell-Chapelure/chapelure.git
    commit: 6c04861ca744f5b2584e6c581b94d87c58579cc4
  - text-display-0.0.1.0
  - haskell-stack-trace-plugin-0.1.3.0