language: haskell

git:
  depth: 5

cabal: "2.4"

cache:
  directories:
  - "$HOME/.cabal/store"

jobs:
  include:
  - ghc: 8.10.7

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - cabal v2-update
  - cabal v2-configure --enable-tests --enable-benchmarks --test-show-details=direct
  - cabal v2-build all

script:
  - echo 'No tests'

notifications:
  email: false
